SCRUM-15 added service and controller for class user and Test for use…
FartushkoY/OnlineShopForHomeAndGarden pull request #16
Opened 2024-08-15 07:22 UTC by IrynaKosiak7

…rService

2024-08-15 08:10 UTC, FartushkoY requested changes
Не согласна с методом сервиса addUser. Его нужно создать, а ты ищешь его среди уже созданных юзеров. Кроме того, при создании юзера id мы же не знаем, он генерируется автоматическию Мы должны полученный ДТО преобразовать в Entity, проверить, нет ли уже юзера с таким e-mail , потом назначить роль и сохранить. И тест у тебя написан для addOrUpdate
и еще, в ДТО юзера для создания нового юзера id не нужен, ведь мы его не задаем

2024-08-16 08:30 UTC, FartushkoY requested changes
1. в Entity Cart не нужно инициализировать Set
2. В валидации номера телефона, если ты прописываешь +49, то потом остается 11 цифр). И там  квадратная скобка открыта и не закрыта
3. В Entity Cart и во все остальные надо добавить @Table(name = "cart") - имя, как в БД
4. Метод добавления юзера я бы все же назвала addUser - это, вроде как, общепринятая практика. 
5. Метод по проверке на наличие юзера с таким e-mail в репозитории ты создала, но не использовала его в сервисе.
6. В тесте при создании CUSTOMER вхоящее значение роли должно быть null, ведь значение CUSTOMER присвоит уже сам метод после проверки. А так у тебя тест не заходит в ту часть метода, где проверяется значение роли

2024-08-16 09:33 UTC, IrynaKosiak7 commented
> 1. в Entity Cart  инициализацию убрала
> 2. Скобочек хватает, регулярное выражение проверила
> 3.  @table(name = "") в сущностях добавлены
> 4. Мутод может называться иначе, если передает суть
> 5. e-mail стоит с аннотацией уникальный и не дает возмоности создавать юзера с таким же, даже если те же буквы в разном регистре 
> 6. С тестом на null есть вопросы, так как не пропускает проверку, но в Postman все запросы отрабатываются корректно

2024-08-19 09:49 UTC, VoytovychM approved these changes

2024-08-19 09:52 UTC, VoytovychM approved these changes

2024-08-19 09:54 UTC, FartushkoY approved these changes

2024-08-19 09:54 UTC, merged