Scrum 47 realisation method and test delete user
FartushkoY/OnlineShopForHomeAndGarden pull request #27
Opened 2024-08-21 10:55 UTC by IrynaKosiak7

2024-08-21 21:15 UTC, FartushkoY requested changes

2024-08-21 21:15 UTC, FartushkoY commented on src/main/java/de/telran/onlineshopforhomeandgarden1/service/UserService.java
> +            cartRepository.deleteById(optional.get().getId());
Ира, да, все работает, если убрать отдельное удаление корзины - проверила.

И тест тогда тоже немного нужно переписать

2024-08-22 11:04 UTC, IrynaKosiak7 commented on src/main/java/de/telran/onlineshopforhomeandgarden1/service/UserService.java
> +            cartRepository.deleteById(optional.get().getId());
сделано. Проверку на 404 тоже

2024-08-23 08:16 UTC, FartushkoY commented on src/test/java/de/telran/onlineshopforhomeandgarden1/service/UserServiceTest.java
>          user.setRole(Role.CUSTOMER);
строка 56 не нужна в тесте, это происходит на уровне сервиса

2024-08-23 08:27 UTC, FartushkoY commented on src/main/java/de/telran/onlineshopforhomeandgarden1/controller/UserController.java
> +            return new ResponseEntity<>(result, result.getName() != null || result.getPhoneNumber() != null ? HttpStatus.OK : HttpStatus.NOT_FOUND);
все же здесь нужно проверять условие result != null ( не result.getName() != null || result.getPhoneNumber() != null) , ведь если сервис не найдет юзера с заданным id, то он вернет пустой Optional, а значит, result будет null

2024-08-23 08:30 UTC, FartushkoY commented on src/main/java/de/telran/onlineshopforhomeandgarden1/controller/UserController.java
> +    public ResponseEntity<String> deleteUser (@PathVariable("userId") Long userId){
ResponseEntity<String> Зачем здесь String?

2024-08-23 08:35 UTC, FartushkoY commented on src/test/java/de/telran/onlineshopforhomeandgarden1/service/UserServiceTest.java
> +        Optional<UserDto> resultOptional = service.updateUser(user.getId(), user.getName(), user.getPhoneNumber());
тут мы должны передать новые значения имени и номера телефона, а не взять их из исходного юзера

2024-08-30 09:06 UTC, FartushkoY approved these changes

2024-08-30 09:07 UTC, merged