SCRUM-64, SCRUM-58 add user request dto and user response dto and logger for user
FartushkoY/OnlineShopForHomeAndGarden pull request #43
Opened 2024-08-30 09:22 UTC by IrynaKosiak7

2024-09-03 15:54 UTC, FartushkoY commented on src/main/java/de/telran/onlineshopforhomeandgarden1/mapper/UserMapper.java
> +    User dtoToRequestEntity (UserRequestDto UserRequestDto);
должно быть requestDtoToEntity

2024-09-03 15:55 UTC, FartushkoY commented on src/main/java/de/telran/onlineshopforhomeandgarden1/mapper/UserMapper.java
> +    User dtoToResponseEntity(UserResponseDto UserDto);
должно быть responseDtoToEntity

2024-09-03 16:22 UTC, FartushkoY requested changes
в тесте savedUser() последняя часть теста не единообразна с предыдущими

и мы говорили насчет логирования, что избыточно не логируем и использовать уровень debug, warning в этих случаях не используем

2024-09-03 16:37 UTC, IrynaKosiak7 commented
ок, тест переделаю.
Изменения для логирования в #47 он создан от этой ветки

2024-09-04 14:44 UTC, FartushkoY submitted a review, later dismissed

2024-09-04 15:27 UTC, IrynaKosiak7 commented on src/main/java/de/telran/onlineshopforhomeandgarden1/mapper/UserMapper.java
> +    User dtoToResponseEntity(UserResponseDto UserDto);
готово

2024-09-04 15:27 UTC, IrynaKosiak7 commented on src/main/java/de/telran/onlineshopforhomeandgarden1/mapper/UserMapper.java
> +    User dtoToRequestEntity (UserRequestDto UserRequestDto);
готово

2024-09-04 16:13 UTC, FartushkoY approved these changes

2024-09-04 16:13 UTC, merged