added classes for Scrum -6,7,8 and updated project
FartushkoY/OnlineShopForHomeAndGarden pull request #8
Opened 2024-08-10 14:45 UTC by IrynaKosiak7

2024-08-11 10:01 UTC, FartushkoY requested changes
1.	В классах Cart  и CartItem  ты забыла добавить (strategy = GenerationType.IDENTITY)
2.	Регулярное выражение для e-mail не работает (лишний слэш перед точкой и в конце \n не нужен). Проверить можно тут https://regex101.com/
3.	В Entity СartItem у поля Product должа же быть @JsonManagedReference(“product”)? Или ты это позже будешь добавлять? 
И тут же, нужно ли fetch = FetchType.LAZY ? Ведь нам при выводе инфо нужна будет  инфо по товарам, СartItem как раз для этого и существует, чтобы увидеть товары в корзине
4.	В СartItemMapper ошибочка в стр 8 и 9 ( тип данных должен быть не СartItemMapper, а СartItemDto

2024-08-11 14:25 UTC, IrynaKosiak7 commented
1,4 пофиксила, спасибо за заметку.
 2 - там нудны два слеша перед "." так, как  двойная косая черта используется, чтобы указать компилятору Java, что это элемент регулярки. \n не нужен, спасибо.

2024-08-11 16:18 UTC, FartushkoY commented
по точке не согласна. Не работает с двойным слешем. проверь. Для указания на то, что сейчас будет символ используется 1 слеш

2024-08-12 09:33 UTC, VoytovychM approved these changes, later dismissed

2024-08-12 09:35 UTC, FartushkoY approved these changes

2024-08-12 09:35 UTC, merged

2024-08-12 09:35 UTC, VoytovychM approved these changes